apiVersion: apps/v1
kind: Deployment
metadata:
  name: podman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podman
  template:
    metadata:
      labels:
        app: podman
    spec:
      containers:
      - name: podman
        image: podman:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
        securityContext:
          privileged: true
